name: sample
description: skeleton for apps that will use modular plugin
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.3
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  flutter_modular: ^1.2.4
  flutter_project_package:
    git:
      url: https://github.com/GitHubStuff/flutter_project_package.git
  # App specific

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
